# Generated by Django 4.1.8 on 2023-11-07 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=120)),
                ('agree', models.BooleanField(default=False)),
                ('first_name1', models.CharField(max_length=255)),
                ('last_name1', models.CharField(max_length=255)),
                ('gender1', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1)),
                ('phone1', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit phone number.')])),
                ('email1', models.CharField(max_length=255)),
                ('education1', models.CharField(max_length=255)),
                ('student_number1', models.CharField(max_length=20)),
                ('first_name2', models.CharField(max_length=255)),
                ('last_name2', models.CharField(max_length=255)),
                ('gender2', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1)),
                ('phone2', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit phone number.')])),
                ('email2', models.CharField(max_length=255)),
                ('education2', models.CharField(max_length=255)),
                ('student_number2', models.CharField(max_length=20)),
                ('first_name3', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name3', models.CharField(blank=True, max_length=255, null=True)),
                ('gender3', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True)),
                ('phone3', models.CharField(blank=True, max_length=11, null=True)),
                ('email3', models.CharField(blank=True, max_length=255, null=True)),
                ('education3', models.CharField(blank=True, max_length=255, null=True)),
                ('student_number3', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['team_name', 'university', 'language'],
            },
        ),
    ]
