# Generated by Django 4.1.8 on 2023-11-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_team_options_alter_team_agree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_date', 'team_name', 'language'], 'verbose_name': 'تیم', 'verbose_name_plural': 'تیم ها'},
        ),
        migrations.AlterField(
            model_name='team',
            name='education1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='education2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_number1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_number2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام دانشگاه'),
        ),
    ]
